-------LOCALDB
--p197

SELECT USERNAME , HEIGHT
FROM USERTBL
WHERE HEIGHT > 177;

SELECT HEIGHT FROM USERTBL WHERE USERNAME='김경호';

SELECT USERNAME, HEIGHT
FROM USERTBL
WHERE HEIGHT > (SELECT HEIGHT FROM USERTBL WHERE USERNAME='김경호');

--동명이인(김경호)추가 
INSERT INTO USERTBL VALUES('KKH2','김경호',2000,'제주','010','11111111',180,'20-1-5');

COMMIT;

--ALL : 결과값 모두만족 후 추출 , MAX함수 사용가능 
SELECT USERNAME, HEIGHT
FROM USERTBL
WHERE HEIGHT > ALL(SELECT HEIGHT FROM USERTBL WHERE USERNAME='김경호');

SELECT USERNAME, HEIGHT
FROM USERTBL
WHERE HEIGHT > (SELECT MAX(HEIGHT) FROM USERTBL WHERE USERNAME='김경호');

--ANY : 결과값 하나이상 만족 후 추출 ,MIN함수 사용가능 
SELECT USERNAME, HEIGHT
FROM USERTBL
WHERE HEIGHT > ANY(SELECT HEIGHT FROM USERTBL WHERE USERNAME='김경호');

SELECT USERNAME, HEIGHT
FROM USERTBL
WHERE HEIGHT > (SELECT MIN(HEIGHT) FROM USERTBL WHERE USERNAME='김경호');

SELECT HEIGHT FROM USERTBL WHERE ADDR='경남';

SELECT USERNAME, HEIGHT
FROM USERTBL
WHERE HEIGHT > ALL(SELECT HEIGHT FROM USERTBL WHERE ADDR='경남');

SELECT USERNAME, HEIGHT
FROM USERTBL
WHERE HEIGHT > ANY(SELECT HEIGHT FROM USERTBL WHERE ADDR='경남');

-- =ANY : IN으로 사용가능
SELECT USERNAME, HEIGHT
FROM USERTBL
WHERE HEIGHT = ANY(SELECT HEIGHT FROM USERTBL WHERE ADDR='경남');

SELECT USERNAME, HEIGHT
FROM USERTBL
WHERE HEIGHT IN(SELECT HEIGHT FROM USERTBL WHERE ADDR='경남');

 --SOME 
 