--쿼리 14
SELECT ABS(-78), ABS(78)
FROM DUAL;

SELECT ROUND (4.852,1) 
FROM DUAL;

SELECT CUSTID, AVG(SALEPRICE)"평균가"
FROM ORDERS
GROUP BY CUSTID;

SELECT CUSTID, ROUND(AVG(SALEPRICE),-3)"평균가"
FROM ORDERS
GROUP BY CUSTID;

SELECT BOOK.*, REPLACE(BOOKNAME,'야구','농구')"변경제목"
FROM BOOK;

SELECT * FROM BOOK;

SELECT BOOKNAME,LENGTH (BOOKNAME)"제목 글자 수", LENGTHB (BOOKNAME) "제목 바이트 수"
FROM BOOK
WHERE PUBLISHER='굿스포츠';

INSERT INTO CUSTOMER VALUES (7,'김대우','대한민국 대구','010-1234-1234');
INSERT INTO CUSTOMER VALUES (8,'이원석','대한민국 대구','010-3332-3332');
INSERT INTO CUSTOMER VALUES (9,'박치국','대한민국 서울','010-4444-4444');
INSERT INTO CUSTOMER VALUES (10,'오재원','대한민국 서울','010-5555-5555');

COMMIT;

SELECT NAME,SUBSTR(NAME,1,1) FROM CUSTOMER;


SELECT SUBSTR(NAME,1,1) || '씨' "성씨", COUNT(*) "인원수"
FROM CUSTOMER
GROUP BY SUBSTR(NAME,1,1)
ORDER BY 인원수 DESC;

SELECT ORDERID, ORDERDATE, ORDERDATE+10 "확정일자"
FROM ORDERS;

--쿼리 15

SELECT TO_CHAR (SYSDATE, 'YYYY-MM-DD HH24:MI:SS DAY MONTH') FROM DUAL;

SELECT ORDERID, TO_CHAR (ORDERDATE ,'YYYY-MM-DD DY'), CUSTID
FROM ORDERS 
WHERE ORDERDATE='20-7-7';

SELECT TO_CHAR (SYSDATE, 'YYYY-MM-DD HH24:MI:SS DAY') FROM DUAL;



---------LOCALHR
-- AVG함수는 COMMISSION_PCT의 NULL 제외 후 평균계산, 
-- COUNT(COMMISSION_PCT) : NULL제외 카운트
--쿼리 16
SELECT SUM(COMMISSION_PCT), AVG(COMMISSION_PCT), SUM(COMMISSION_PCT)/ COUNT(*),
        SUM(COMMISSION_PCT)/ COUNT(COMMISSION_PCT)
FROM EMPLOYEES;

--DEPARTMENT_ID : 필드 NUMBER -> TO_CHAR로 변환
SELECT EMPLOYEE_ID, FIRST_NAME, PHONE_NUMBER, NVL(TO_CHAR(DEPARTMENT_ID),'부서미지정')
FROM EMPLOYEES;

SELECT DEPARTMENTS.* , NVL(TO_CHAR (MANAGER_ID), '매니저 없음')
FROM DEPARTMENTS;


--NVL2 (필드, 필드NULL아닐때, NULL일때)
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY,COMMISSION_PCT,
NVL2(COMMISSION_PCT,(SALARY+SALARY*COMMISSION_PCT),SALARY)"연봉"
FROM EMPLOYEES;


--CASE 문 (문자형 변환O)

SELECT EMPLOYEE_ID, FIRST_NAME, PHONE_NUMBER,
    CASE 
    WHEN (TO_CHAR (DEPARTMENT_ID)) IS NULL THEN '부서 미정'
    ELSE (TO_CHAR (DEPARTMENT_ID))
    END "부서명"
FROM EMPLOYEES;

--DECODE문 

SELECT EMPLOYEE_ID, FIRST_NAME, PHONE_NUMBER,
DECODE (DEPARTMENT_ID, NULL, '부서 미정',DEPARTMENT_ID) "부서명"
FROM EMPLOYEES;

--NVL2 (문자형 변환O)
SELECT EMPLOYEE_ID, FIRST_NAME, PHONE_NUMBER, 
NVL2(TO_CHAR(DEPARTMENT_ID),TO_CHAR(DEPARTMENT_ID), '부서미정') "부서명"
FROM EMPLOYEES;


--CASE 
SELECT DEPARTMENTS.*,
    CASE
    WHEN TO_CHAR (MANAGER_ID) IS NOT NULL THEN TO_CHAR(MANAGER_ID)
    ELSE '매니저 없음'
END "매니저"
FROM DEPARTMENTS;

--DECODE
SELECT DEPARTMENTS.*,
DECODE (MANAGER_ID, NULL, '매니저 없음',MANAGER_ID) "매니저"
FROM DEPARTMENTS;

--NVL2 (문자형 변환O)
SELECT DEPARTMENTS.*,
NVL2(TO_CHAR (MANAGER_ID),TO_CHAR (MANAGER_ID), '매니저 없음') "매니저"
FROM DEPARTMENTS;

--CASE 
SELECT EMPLOYEE_ID , LAST_NAME || ' ' || FIRST_NAME, JOB_ID, SALARY,
    CASE JOB_ID
    WHEN 'HR_REP' THEN SALARY*1.1
    WHEN 'MK_REP' THEN SALARY*1.12
    WHEN 'PR_REP' THEN SALARY*1.15
    WHEN 'SA_REP' THEN SALARY*1.18
    WHEN 'IT_PROG' THEN SALARY*1.2
    ELSE SALARY
    END "NEW SALARY"
FROM EMPLOYEES;

--DECODE
SELECT EMPLOYEE_ID , LAST_NAME || ' ' || FIRST_NAME, JOB_ID, SALARY,
    DECODE (JOB_ID,'HR_REP', SALARY*1.1, 'MK_REP' ,SALARY*1.12, 'PR_REP' ,SALARY*1.15,
    'SA_REP' ,SALARY*1.18, 'IT_PROG' , SALARY*1.2)  "NEW SALARY"
FROM EMPLOYEES;

-------LOCALMADANG
--NVR (필드:문자형에서만 가능)
--쿼리 16

SELECT CUSTID, NAME, ADDRESS, NVL (PHONE,'전화번호없음')
FROM CUSTOMER;

--쿼리 17

SELECT CUSTID, NAME, ADDRESS, NVL (PHONE,'전화번호없음')
FROM CUSTOMER;

SELECT CUSTID, NAME, ADDRESS, NVL2 (PHONE,PHONE,'전화번호없음')
FROM CUSTOMER;

--CASE 문

SELECT NAME,
    CASE 
    WHEN PHONE IS NULL THEN '연락처 없음'
    ELSE PHONE
    END "연락처"
FROM CUSTOMER;

--DECODE 문

SELECT NAME, DECODE (PHONE, NULL, '연락처 없음',PHONE)"연락처"
FROM CUSTOMER;


