-- 연습문제

SELECT ABS(-15) FROM DUAL;
SELECT CEIL (15.7), CEIL(-15.7) FROM DUAL;
SELECT COS(3.14159) FROM DUAL;
SELECT FLOOR(15.7), FLOOR(-15.7) FROM DUAL;
SELECT LOG(10,100) FROM DUAL;
SELECT MOD(11,4) FROM DUAL;
SELECT POWER(3,2) FROM DUAL;
SELECT ROUND (15.7), ROUND (-15.7) FROM DUAL;
SELECT SIGN(-15), SIGN(15) FROM DUAL;
SELECT TRUNC(15.7), TRUNC(-15.7)  FROM DUAL;
SELECT CHR(67) FROM DUAL;
SELECT CONCAT('HAPPY ', 'Birthday') FROM DUAL;
SELECT LOWER('Birthday') ,UPPER('Birthday')FROM DUAL;
SELECT LPAD('Page 1', 15, '*.') ,RPAD('Page 2', 15, '*') FROM DUAL;
SELECT LTRIM(' Page 1 '), LENGTH(LTRIM(' Page 1 ')) ,TRIM(' Page 1 '),LENGTH(TRIM(' Page 1 '))
FROM DUAL;
SELECT LTRIM('001234', '0'),LTRIM('ababcdef', 'ab'),RTRIM('pass', 's'),
       RTRIM('010103-*******', '*')
FROM DUAL;
SELECT REPLACE('JACK', 'J', 'BL') FROM DUAL;
SELECT SUBSTR('ABCDEFG', 3, 4) FROM DUAL;
SELECT TRIM(LEADING 0 FROM '00AA00') FROM DUAL;
SELECT INSTR('CORPORATE FLOOR','OR', 3, 2) FROM DUAL;
SELECT LENGTH('Birthday') FROM DUAL;
SELECT ADD_MONTHS('14/05/21', 1)FROM DUAL;
SELECT LAST_DAY(SYSDATE) FROM DUAL;
SELECT NEXT_DAY(SYSDATE, '수') FROM DUAL;
SELECT ROUND(SYSDATE) FROM DUAL;
SELECT SYSDATE FROM DUAL;
SELECT TO_CHAR(SYSDATE), TO_CHAR(123) FROM DUAL;
SELECT TO_DATE('12 05 2014', 'DD MM YYYY') FROM DUAL;
SELECT TO_NUMBER('12.3')FROM DUAL;
SELECT DECODE('M','M','남자','여자'),DECODE('F','M','남자','여자') FROM DUAL;
SELECT NULLIF(123, 345) FROM DUAL;
SELECT NVL(NULL, 123) ,NVL(1, 123), NVL2(1,333,666),NVL2(NULL,333,777) FROM DUAL;
SELECT INITCAP('abced') FROM DUAL;



ALTER TABLE CUSTOMER
ADD SEX CHAR(1) DEFAULT 'M' NOT NULL 
CHECK (SEX IN ('M','F'));

UPDATE CUSTOMER
SET SEX='F'
WHERE CUSTID IN (2,3,5);

SELECT *,
DECODE (SEX, F, '여자','남자')"성별"
FROM CUSTOMER; 

SELECT *,
    CASE
    WHEN (SEX) IS 'F' THEN '여자'
    ELSE '남자'
END "성별"
FROM CUSTOMER;




