-- 연습문제

SELECT ABS(-15) FROM DUAL;
SELECT CEIL (15.7), CEIL(-15.7) FROM DUAL;
SELECT COS(3.14159) FROM DUAL;
SELECT FLOOR(15.7), FLOOR(-15.7) FROM DUAL;
SELECT LOG(10,100) FROM DUAL;
SELECT MOD(11,4) FROM DUAL;
SELECT POWER(3,2) FROM DUAL;
SELECT ROUND (15.7), ROUND (-15.7) FROM DUAL;
SELECT SIGN(-15), SIGN(15) FROM DUAL;
SELECT TRUNC(15.7), TRUNC(-15.7)  FROM DUAL;
SELECT CHR(67) FROM DUAL;
SELECT CONCAT('HAPPY ', 'Birthday') FROM DUAL;
SELECT LOWER('Birthday') ,UPPER('Birthday')FROM DUAL;
SELECT LPAD('Page 1', 15, '*.') ,RPAD('Page 2', 15, '*') FROM DUAL;
SELECT LTRIM(' Page 1 '), LENGTH(LTRIM(' Page 1 ')) ,TRIM(' Page 1 '),LENGTH(TRIM(' Page 1 '))
FROM DUAL;
SELECT LTRIM('001234', '0'),LTRIM('ababcdef', 'ab'),RTRIM('pass', 's'),
       RTRIM('010103-*******', '*')
FROM DUAL;
SELECT REPLACE('JACK', 'J', 'BL') FROM DUAL;
SELECT SUBSTR('ABCDEFG', 3, 4) FROM DUAL;
SELECT TRIM(LEADING 0 FROM '00AA00') FROM DUAL;
SELECT INSTR('CORPORATE FLOOR','OR', 3, 2) FROM DUAL;
SELECT LENGTH('Birthday') FROM DUAL;
SELECT ADD_MONTHS('14/05/21', 1)FROM DUAL;
SELECT LAST_DAY(SYSDATE) FROM DUAL;
SELECT NEXT_DAY(SYSDATE, '수') FROM DUAL;
SELECT ROUND(SYSDATE) FROM DUAL;
SELECT SYSDATE FROM DUAL;
SELECT TO_CHAR(SYSDATE), TO_CHAR(123) FROM DUAL;
SELECT TO_DATE('12 05 2014', 'DD MM YYYY') FROM DUAL;
SELECT TO_NUMBER('12.3')FROM DUAL;
SELECT DECODE('M','M','남자','여자'),DECODE('F','M','남자','여자') FROM DUAL;
SELECT NULLIF(123, 345) FROM DUAL;
SELECT NVL(NULL, 123) ,NVL(1, 123), NVL2(1,333,666),NVL2(NULL,333,777) FROM DUAL;
SELECT INITCAP('abced') FROM DUAL;




-----localMADANG

ALTER TABLE CUSTOMER
ADD SEX CHAR(1) DEFAULT 'M' NOT NULL 
CHECK (SEX IN ('M','F'));

UPDATE CUSTOMER
SET SEX='F'
WHERE CUSTID IN (2,3,5);

SELECT NAME, PHONE,
DECODE (SEX, 'F', '여자','남자')
FROM CUSTOMER; 

SELECT NAME, PHONE,
    CASE SEX
    WHEN 'F' THEN '여자'
    ELSE '남자'
END SEX      -- "별칭" : 공백이 있을 경우, 별칭 : ""없이도 사용가능!!
FROM CUSTOMER;




-------localhr

SELECT EMPLOYEE_ID, (LAST_NAME ||' '|| FIRST_NAME)NAME, 
    CASE
    WHEN JOB_ID LIKE 'IT%' THEN SALARY*1.123
    ELSE SALARY
    END "INCREASED SALARUY"
FROM EMPLOYEES
ORDER BY 'INCREASEDSALARUY' DESC;

-- DECODE 함수X
/*SELECT EMPLOYEE_ID,(LAST_NAME ||' '|| FIRST_NAME)NAME,
DECODE (JOB_ID, JOB_ID LIKE 'IT%',SALARY*1.123 ,SALARY)
FROM EMPLOYEES 
ORDER BY 'INCREASEDSALARUY' DESC;*/

SELECT INITCAP(LAST_NAME) || ' ' || INITCAP(FIRST_NAME) || 'is a ' || job_id 
"emplyee job"
FROM EMPLOYEES;


SELECT INITCAP(LAST_NAME) || ' ' || INITCAP(FIRST_NAME)NAME ,SALARY, COMMISSION_PCT,
NVL2(TO_CHAR (COMMISSION_PCT),TO_CHAR((SALARY+COMMISSION_PCT*SALARY)),'SALARY ONLY')COMSALARY
FROM EMPLOYEES
ORDER BY COMSALARY;

SELECT INITCAP(LAST_NAME) || ' ' || INITCAP(FIRST_NAME)NAME,SALARY, COMMISSION_PCT,
    CASE
    WHEN COMMISSION_PCT IS NULL THEN 'SALARY ONLY'
    ELSE TO_CHAR (SALARY+COMMISSION_PCT*SALARY)
    END COMSALARY
FROM EMPLOYEES;



SELECT INITCAP(LAST_NAME) || ' ' || INITCAP(FIRST_NAME),SALARY, COMMISSION_PCT,
   DECODE (COMMISSION_PCT , NULL, 'SALARY ONLY',SALARY+COMMISSION_PCT*SALARY) COMSALARY
FROM EMPLOYEES
ORDER BY COMSALARY;


SELECT INITCAP(LAST_NAME) || ' ' || INITCAP(FIRST_NAME) NAME, HIRE_DATE, 
TO_CHAR(HIRE_DATE,'DAY')
FROM EMPLOYEES
ORDER BY TO_CHAR(HIRE_DATE, 'D');


